### ISSUE TITLE
issue about datagenerators.py

### ISSUE THREAD

**Issue by 18370029656** [zhangliutong/SPnet#2]
Hello, where should fix and moving be placed when importing the training dataset? Is it directly placed in the same folder/data/train? Or are they placed under/data/train/fix and/data/train/moving respectively?
<img width="694" alt="image" src="https://github.com/zhangliutong/SPnet/assets/108872700/e8c50fda-37fe-4d01-a851-569dfe759569">

**Comment by zhangliutong** [comment]
The training dataset is placed in the same folder. The moving and fixed images are randomly selected.

**Comment by 18370029656** [comment]
ok,thanks for your reply!
